{% set name = "gpp-client" %}
{% set version = "26.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/gpp_client-{{ version }}.tar.gz
  sha256: db90e83ec79786cd462973d4a5996fb9f72e68ea24e18e9e43529c22e9ec7e47

build:
  entry_points:
    - gpp = gpp_client.cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.13.4
    - beautifulsoup4 >=4.11.0
    - graphql-core >=3.2.0
    - httpx >=0.23
    - pydantic >=2.12.0
    - toml >=0.10
    - typer >=0.21.1
    - websockets >=14.2
    - pydantic-settings >=2.13.1
    - click >=8.3.1

test:
  imports:
    - gpp_client
  commands:
    - pip check
    - gpp --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Gemini Program Platform client.
  dev_url: https://github.com/gemini-hlsw/gpp-client
  doc_url: https://gpp-client.readthedocs.io/en/latest/
  home: https://github.com/gemini-hlsw/gpp-client
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - miguelgomezgomez
    - davner
